name: Build and Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "publish"
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install project dependencies
      - name: Install dependencies
        run: npm install --ci

      # Build project
      - name: Build
        run: npm run build
        env:
          REACT_APP_LISTEN_NOTES_API_BASE_URL: ${{ secrets.REACT_APP_LISTEN_NOTES_API_BASE_URL }}
          REACT_APP_LISTEN_NOTES_API_KEY: ${{ secrets.REACT_APP_LISTEN_NOTES_API_KEY }}
          REACT_APP_MAIN_PODCAST_GENRE: ${{ secrets.REACT_APP_MAIN_PODCAST_GENRE }}
        
      # Deploy
      - name: Publish in Surge
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: podcaster-ts.surge.sh
          project: './build'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
